# Population
L: 1000000 # 1 Mb 
N: 1000
# Reproduction
SEX_lst: [0.0, 1.0]
# Recombination
CO: 1.0e-7 # Crossover rate per base pair during sex
GC_lst: [1.0e-06, 5.3367e-07, 2.848e-07, 1.5199e-07, 8.111e-08, 4.329e-08, 2.31e-08, 1.233e-08, 6.58e-09, 3.51e-09, 1.87e-09, 1.0e-09] # 12 rates of gene conversion tract initiation 
TRACT: 5000 # Mean GC tract length of 1 kb; LOH = GC * TRACT
# Mutation
MUT: 5.0e-9 # Mutation rate per base pair per generation
S_MEAN: -0.01
S_SHAPE: 0.2
# Simulation
GENS: 50000
REP_NUM: 100